// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Route$ReactHooksTemplate = require("./Route.bs.js");
var Settings$ReactHooksTemplate = require("./Settings.bs.js");

function Admin$Card(Props) {
  var url = Props.url;
  var name = Props.name;
  return React.createElement("section", {
              style: {
                height: "200px",
                position: "relative",
                width: "300px"
              }
            }, React.createElement("iframe", {
                  style: {
                    height: "100%",
                    width: "100%"
                  },
                  src: url
                }), React.createElement("input", {
                  value: url
                }), React.createElement("h2", undefined, name));
}

var Card = /* module */[/* make */Admin$Card];

function useInput(initialVal) {
  var match = React.useState((function () {
          return initialVal;
        }));
  var setValue = match[1];
  var onChange = function (e) {
    return Curry._1(setValue, e.target.value);
  };
  return /* tuple */[
          match[0],
          onChange
        ];
}

function Admin(Props) {
  var goToHome = function (param) {
    return ReasonReactRouter.push(Route$ReactHooksTemplate.getRoutePath(/* Home */2, true));
  };
  var settings = Settings$ReactHooksTemplate.get(/* () */0);
  React.useState((function () {
          return /* [] */0;
        }));
  var match = useInput("");
  var inputName = match[0];
  var match$1 = useInput("");
  console.log(inputName);
  var handleSubmit = function ($$event) {
    $$event.preventDefault();
    return /* () */0;
  };
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Admin Panel"), React.createElement("a", {
                  href: "javascript:;",
                  onClick: goToHome
                }, "Go Back"), React.createElement("form", {
                  onSubmit: handleSubmit
                }, React.createElement("label", {
                      htmlFor: "frame-name"
                    }, "Name: "), React.createElement("input", {
                      id: "frame-name",
                      value: inputName,
                      onChange: match[1]
                    }), React.createElement("label", {
                      htmlFor: "frame-url"
                    }, "URL: "), React.createElement("input", {
                      id: "frame-url",
                      value: match$1[0],
                      onChange: match$1[1]
                    }), React.createElement("button", undefined, "Submit")), React.createElement("section", undefined, $$Array.of_list(List.map((function (frame) {
                            return React.createElement(Admin$Card, {
                                        url: frame[/* url */1],
                                        name: frame[/* name */0],
                                        key: frame[/* url */1]
                                      });
                          }), settings[/* frames */0]))));
}

var make = Admin;

exports.Card = Card;
exports.useInput = useInput;
exports.make = make;
/* react Not a pure module */
