// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Route$ReactHooksTemplate = require("./Route.bs.js");

function Admin(Props) {
  var goToHome = function (param) {
    return ReasonReactRouter.push(Route$ReactHooksTemplate.getRoutePath(/* Home */2, true));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Admin Panel"), React.createElement("a", {
                  href: "javascript:;",
                  onClick: goToHome
                }, "Go Back"));
}

var make = Admin;

exports.make = make;
/* react Not a pure module */
