// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Route$ReactHooksTemplate = require("./Route.bs.js");
var Settings$ReactHooksTemplate = require("./Settings.bs.js");

function Home(Props) {
  var goAdmin = function (_e) {
    return ReasonReactRouter.push(Route$ReactHooksTemplate.getRoutePath(/* Admin */1, true));
  };
  var settings = Settings$ReactHooksTemplate.get(/* () */0);
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Home Page"), React.createElement("a", {
                  href: "javascript:;",
                  onClick: goAdmin
                }, "Go Admin"), React.createElement("ul", undefined, $$Array.of_list(List.map((function (frame) {
                            return React.createElement("li", {
                                        key: frame[/* url */1]
                                      }, React.createElement("h1", undefined, frame[/* name */0]), React.createElement("a", {
                                            href: frame[/* url */1]
                                          }, frame[/* url */1]));
                          }), settings[/* frames */0]))));
}

var make = Home;

exports.make = make;
/* react Not a pure module */
