// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


function getRoutePath(route, withHash) {
  var result;
  switch (route) {
    case 0 : 
        result = "";
        break;
    case 1 : 
        result = "admin";
        break;
    case 2 : 
        result = "home";
        break;
    
  }
  if (withHash) {
    return "/#" + result;
  } else {
    return result;
  }
}

function getRouteByHash(hash) {
  switch (hash) {
    case "admin" : 
        return /* Admin */1;
    case "home" : 
        return /* Home */2;
    default:
      return /* NotFound */0;
  }
}

exports.getRoutePath = getRoutePath;
exports.getRouteByHash = getRouteByHash;
/* No side effect */
