// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


var localStorageNameSpace = "__ewall__";

var defaultSettings = /* record */[/* frames : [] */0];

function set(settings) {
  var match = JSON.stringify(settings);
  if (match !== undefined) {
    localStorage.setItem(localStorageNameSpace, match);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function get(param) {
  var match = localStorage.getItem(localStorageNameSpace);
  if (match !== null) {
    return JSON.parse(match);
  } else {
    return defaultSettings;
  }
}

exports.localStorageNameSpace = localStorageNameSpace;
exports.defaultSettings = defaultSettings;
exports.set = set;
exports.get = get;
/* No side effect */
